// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/ctrl/ctrl.go
//
// Generated by this command:
//
//	mockgen -source=./internal/ctrl/ctrl.go -destination=tests/mocks/mock_ctrl.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/JMURv/org-struct/internal/dto"
	models "github.com/JMURv/org-struct/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAppRepo is a mock of AppRepo interface.
type MockAppRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAppRepoMockRecorder
	isgomock struct{}
}

// MockAppRepoMockRecorder is the mock recorder for MockAppRepo.
type MockAppRepoMockRecorder struct {
	mock *MockAppRepo
}

// NewMockAppRepo creates a new mock instance.
func NewMockAppRepo(ctrl *gomock.Controller) *MockAppRepo {
	mock := &MockAppRepo{ctrl: ctrl}
	mock.recorder = &MockAppRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppRepo) EXPECT() *MockAppRepoMockRecorder {
	return m.recorder
}

// CreateDepartment mocks base method.
func (m *MockAppRepo) CreateDepartment(ctx context.Context, req dto.CreateDepartmentRequest) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", ctx, req)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockAppRepoMockRecorder) CreateDepartment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockAppRepo)(nil).CreateDepartment), ctx, req)
}

// CreateEmployee mocks base method.
func (m *MockAppRepo) CreateEmployee(ctx context.Context, id uint64, req dto.CreateDepartmentEmployeeRequest) (*models.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", ctx, id, req)
	ret0, _ := ret[0].(*models.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockAppRepoMockRecorder) CreateEmployee(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockAppRepo)(nil).CreateEmployee), ctx, id, req)
}

// DeleteDepartment mocks base method.
func (m *MockAppRepo) DeleteDepartment(ctx context.Context, id uint64, req dto.DeleteDepartmentQuery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartment", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartment indicates an expected call of DeleteDepartment.
func (mr *MockAppRepoMockRecorder) DeleteDepartment(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartment", reflect.TypeOf((*MockAppRepo)(nil).DeleteDepartment), ctx, id, req)
}

// GetDepartment mocks base method.
func (m *MockAppRepo) GetDepartment(ctx context.Context, id uint64, req dto.GetDepartmentQuery) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartment", ctx, id, req)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartment indicates an expected call of GetDepartment.
func (mr *MockAppRepoMockRecorder) GetDepartment(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartment", reflect.TypeOf((*MockAppRepo)(nil).GetDepartment), ctx, id, req)
}

// UpdateDepartment mocks base method.
func (m *MockAppRepo) UpdateDepartment(ctx context.Context, id uint64, req dto.UpdateDepartmentRequest) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartment", ctx, id, req)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDepartment indicates an expected call of UpdateDepartment.
func (mr *MockAppRepoMockRecorder) UpdateDepartment(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartment", reflect.TypeOf((*MockAppRepo)(nil).UpdateDepartment), ctx, id, req)
}

// MockAppCtrl is a mock of AppCtrl interface.
type MockAppCtrl struct {
	ctrl     *gomock.Controller
	recorder *MockAppCtrlMockRecorder
	isgomock struct{}
}

// MockAppCtrlMockRecorder is the mock recorder for MockAppCtrl.
type MockAppCtrlMockRecorder struct {
	mock *MockAppCtrl
}

// NewMockAppCtrl creates a new mock instance.
func NewMockAppCtrl(ctrl *gomock.Controller) *MockAppCtrl {
	mock := &MockAppCtrl{ctrl: ctrl}
	mock.recorder = &MockAppCtrlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppCtrl) EXPECT() *MockAppCtrlMockRecorder {
	return m.recorder
}

// CreateDepartment mocks base method.
func (m *MockAppCtrl) CreateDepartment(ctx context.Context, req dto.CreateDepartmentRequest) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", ctx, req)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockAppCtrlMockRecorder) CreateDepartment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockAppCtrl)(nil).CreateDepartment), ctx, req)
}

// CreateEmployee mocks base method.
func (m *MockAppCtrl) CreateEmployee(ctx context.Context, id uint64, req dto.CreateDepartmentEmployeeRequest) (*models.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", ctx, id, req)
	ret0, _ := ret[0].(*models.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockAppCtrlMockRecorder) CreateEmployee(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockAppCtrl)(nil).CreateEmployee), ctx, id, req)
}

// DeleteDepartment mocks base method.
func (m *MockAppCtrl) DeleteDepartment(ctx context.Context, id uint64, req dto.DeleteDepartmentQuery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartment", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartment indicates an expected call of DeleteDepartment.
func (mr *MockAppCtrlMockRecorder) DeleteDepartment(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartment", reflect.TypeOf((*MockAppCtrl)(nil).DeleteDepartment), ctx, id, req)
}

// GetDepartment mocks base method.
func (m *MockAppCtrl) GetDepartment(ctx context.Context, id uint64, req dto.GetDepartmentQuery) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartment", ctx, id, req)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartment indicates an expected call of GetDepartment.
func (mr *MockAppCtrlMockRecorder) GetDepartment(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartment", reflect.TypeOf((*MockAppCtrl)(nil).GetDepartment), ctx, id, req)
}

// UpdateDepartment mocks base method.
func (m *MockAppCtrl) UpdateDepartment(ctx context.Context, id uint64, req dto.UpdateDepartmentRequest) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartment", ctx, id, req)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDepartment indicates an expected call of UpdateDepartment.
func (mr *MockAppCtrlMockRecorder) UpdateDepartment(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartment", reflect.TypeOf((*MockAppCtrl)(nil).UpdateDepartment), ctx, id, req)
}
