name: org-struct-prod
services:
  db:
    container_name: db
    image: postgres:17.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: 'psql -w -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -c "SELECT 1"'
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 2s
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    networks: [ org-struct-prod ]

  backend:
    container_name: backend
    restart: unless-stopped
    image: org-struct-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./build/configs/envs/.env.prod
    ports:
      - "${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}"
      - "${SERVER_GRPC_PORT}:${SERVER_GRPC_PORT}"
      - "${SERVER_PROM_PORT}:${SERVER_PROM_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${SERVER_HTTP_PORT}/health" ]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
        restart: true
      minio:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    networks: [ org-struct-prod ]
    develop:
      watch:
        - action: rebuild
          target: /
          path: backend
          ignore:
            - .git
            - vendor

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.71.0
    restart: unless-stopped
    profiles: ["observe"]
    ports:
      - "14268:14268"
      - "16686:16686"
      - "6831:6831/udp"
    networks: [ org-struct-prod ]

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.5.0
    restart: unless-stopped
    profiles: ["observe"]
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks: [ org-struct-prod ]

  node-exp:
    container_name: node-exp
    image: prom/node-exporter:v1.9.1
    restart: unless-stopped
    profiles: ["observe"]
    ports:
      - "9100:9100"
    networks: [ org-struct-prod ]

  grafana:
    container_name: grafana
    image: grafana/grafana:12.0.2
    restart: unless-stopped
    profiles: ["observe"]
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning:ro
    networks: [ org-struct-prod ]

  loki:
    container_name: loki
    image: grafana/loki:main-3ffed72
    restart: unless-stopped
    profiles: ["observe"]
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - loki_data:/loki
      - ./configs/loki:/etc/loki
    networks: [ org-struct-prod ]

  promtail:
    container_name: promtail
    image: grafana/promtail:main-3ffed72
    restart: unless-stopped
    profiles: ["observe"]
    volumes:
      - ./configs/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks: [ org-struct-prod ]

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    profiles: ["observe"]
    environment:
      DATA_SOURCE_NAME: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      db:
        condition: service_healthy
    networks: [ org-struct-prod ]

  redis-exporter:
    image: oliver006/redis_exporter:v1.43.0
    profiles: ["observe"]
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    depends_on:
      redis:
        condition: service_started
    networks: [ org-struct-prod ]


volumes:
  pg_data_prod:
  prometheus_data_prod:
  grafana_data_prod:
  loki_data_prod:

networks:
  org-struct-prod:
    name: org-struct-prod
